/* Generated by reswrap version 3.2.0 */

/* created by reswrap from file PlayButtonGIF.gif */
extern const unsigned char PlayButtonGIF[];

/* created by reswrap from file CycleButtonGIF.gif */
extern const unsigned char CycleButtonGIF[];

/* created by reswrap from file PauseButtonGIF.gif */
extern const unsigned char PauseButtonGIF[];

extern const unsigned char MonitorGIF[];
